name: Build Fabric Mod

on:
  push:
    branches:
      - main  # 주 브랜치 이름에 맞게 수정
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '23'  # Java 23 설정

    - name: Build with Gradle
      run: /gradle build
